// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type SandboxDocumentDataSlicesSlice = Section2Slice | HeroDemoSlice;

/**
 * Content for Sandbox documents
 */
interface SandboxDocumentData {
  /**
   * Title field in *Sandbox*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sandbox.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Sandbox*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sandbox.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SandboxDocumentDataSlicesSlice>; /**
   * Meta Title field in *Sandbox*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sandbox.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Sandbox*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sandbox.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sandbox*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sandbox.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Sandbox document from Prismic
 *
 * - **API ID**: `sandbox`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SandboxDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SandboxDocumentData>,
    "sandbox",
    Lang
  >;

export type AllDocumentTypes = SandboxDocument;

/**
 * Item in *HeroDemo → Default → Primary → Carousal*
 */
export interface HeroDemoSliceDefaultPrimaryCarousalItem {
  /**
   * Images field in *HeroDemo → Default → Primary → Carousal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.carousal[].images
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  images: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroDemo → Default → Primary*
 */
export interface HeroDemoSliceDefaultPrimary {
  /**
   * Carousal field in *HeroDemo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.carousal[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousal: prismic.GroupField<
    Simplify<HeroDemoSliceDefaultPrimaryCarousalItem>
  >;

  /**
   * Heading field in *HeroDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeroDemo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroDemoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroDemoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroDemo*
 */
type HeroDemoSliceVariation = HeroDemoSliceDefault;

/**
 * HeroDemo Shared Slice
 *
 * - **API ID**: `hero_demo`
 * - **Description**: HeroDemo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroDemoSlice = prismic.SharedSlice<
  "hero_demo",
  HeroDemoSliceVariation
>;

/**
 * Primary content in *Section2 → Default → Primary*
 */
export interface Section2SliceDefaultPrimary {
  /**
   * Heading field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Section2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section2*
 */
type Section2SliceVariation = Section2SliceDefault;

/**
 * Section2 Shared Slice
 *
 * - **API ID**: `section2`
 * - **Description**: Section2
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section2Slice = prismic.SharedSlice<
  "section2",
  Section2SliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SandboxDocument,
      SandboxDocumentData,
      SandboxDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroDemoSlice,
      HeroDemoSliceDefaultPrimaryCarousalItem,
      HeroDemoSliceDefaultPrimary,
      HeroDemoSliceVariation,
      HeroDemoSliceDefault,
      Section2Slice,
      Section2SliceDefaultPrimary,
      Section2SliceVariation,
      Section2SliceDefault,
    };
  }
}
