// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

interface ConversionbarDocumentData {}

/**
 * ConversionBar document from Prismic
 *
 * - **API ID**: `conversionbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConversionbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConversionbarDocumentData>,
    "conversionbar",
    Lang
  >;

/**
 * Item in *Footer → Main links*
 */
export interface FooterDocumentDataMainLinksItem {
  /**
   * Links field in *Footer → Main links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.main_links[].links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Footer → Sub Links*
 */
export interface FooterDocumentDataSubLinksItem {
  /**
   * Links field in *Footer → Sub Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.sub_links[].links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Footer → Social Links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Links field in *Footer → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Footer → Testimonials*
 */
export interface FooterDocumentDataTestimonialsItem {
  /**
   * Quote field in *Footer → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.testimonials[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Details field in *Footer → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.testimonials[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Item in *Footer → Contacts*
 */
export interface FooterDocumentDataContactsItem {
  /**
   * Methods field in *Footer → Contacts*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Telephone, Email or Websites
   * - **API ID Path**: footer.contacts[].methods
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  methods: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Footer → Footer Credits*
 */
export interface FooterDocumentDataFooterCreditsItem {
  /**
   * Text One field in *Footer → Footer Credits*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_credits[].text_one
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_one: prismic.RichTextField;

  /**
   * Text Two field in *Footer → Footer Credits*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_credits[].text_two
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_two: prismic.RichTextField;

  /**
   * Text Three field in *Footer → Footer Credits*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_credits[].text_three
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_three: prismic.RichTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Links Tab Title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_tab_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  links_tab_title: prismic.RichTextField;

  /**
   * Main links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.main_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  main_links: prismic.GroupField<Simplify<FooterDocumentDataMainLinksItem>>;

  /**
   * Sub Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.sub_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sub_links: prismic.GroupField<Simplify<FooterDocumentDataSubLinksItem>>;

  /**
   * Social Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;

  /**
   * Footer Legal Links field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_legal_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_legal_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Testimonals Heading field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.testimonals_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonals_heading: prismic.RichTextField;

  /**
   * Testimonials field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.testimonials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<FooterDocumentDataTestimonialsItem>
  >;

  /**
   * Contacts Heading field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contacts_heading: prismic.RichTextField;

  /**
   * Contacts field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contacts: prismic.GroupField<Simplify<FooterDocumentDataContactsItem>>;

  /**
   * Footer Credits field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_credits[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_credits: prismic.GroupField<
    Simplify<FooterDocumentDataFooterCreditsItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Navigation → Menu items*
 */
export interface NavigationDocumentDataMenuItemsItem {
  /**
   * Menu ID field in *Navigation → Menu items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].menu_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_id: prismic.KeyTextField;

  /**
   * Label field in *Navigation → Menu items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Menu items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Has MegaMenu field in *Navigation → Menu items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navigation.menu_items[].has_mega_menu
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  has_mega_menu: prismic.BooleanField;
}

type NavigationDocumentDataSlicesSlice = MegaMenuSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Menu items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_items: prismic.GroupField<Simplify<NavigationDocumentDataMenuItemsItem>>;

  /**
   * Primary CTA field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.primary_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type SandboxDocumentDataSlicesSlice =
  | ConversionPanelSlice
  | Section4Slice
  | Section3Slice
  | Section2Slice
  | HeroDemoSlice;

/**
 * Content for Sandbox documents
 */
interface SandboxDocumentData {
  /**
   * Title field in *Sandbox*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sandbox.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Sandbox*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sandbox.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SandboxDocumentDataSlicesSlice>; /**
   * Meta Title field in *Sandbox*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sandbox.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Sandbox*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sandbox.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sandbox*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sandbox.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Sandbox document from Prismic
 *
 * - **API ID**: `sandbox`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SandboxDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SandboxDocumentData>,
    "sandbox",
    Lang
  >;

export type AllDocumentTypes =
  | ConversionbarDocument
  | FooterDocument
  | NavigationDocument
  | SandboxDocument;

/**
 * Item in *ConversionPanel → Default → Primary → Panel*
 */
export interface ConversionPanelSliceDefaultPrimaryPanelItem {
  /**
   * Logo field in *ConversionPanel → Default → Primary → Panel*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: conversion_panel.default.primary.panel[].logo
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  logo: prismic.BooleanField;

  /**
   * Heading field in *ConversionPanel → Default → Primary → Panel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conversion_panel.default.primary.panel[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Link field in *ConversionPanel → Default → Primary → Panel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: conversion_panel.default.primary.panel[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Dropdown Links field in *ConversionPanel → Default → Primary → Panel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: conversion_panel.default.primary.panel[].dropdown_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dropdown_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Button Link field in *ConversionPanel → Default → Primary → Panel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: conversion_panel.default.primary.panel[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Search Bar field in *ConversionPanel → Default → Primary → Panel*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: conversion_panel.default.primary.panel[].search_bar
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  search_bar: prismic.BooleanField;
}

/**
 * Primary content in *ConversionPanel → Default → Primary*
 */
export interface ConversionPanelSliceDefaultPrimary {
  /**
   * Panel field in *ConversionPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: conversion_panel.default.primary.panel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  panel: prismic.GroupField<
    Simplify<ConversionPanelSliceDefaultPrimaryPanelItem>
  >;
}

/**
 * Default variation for ConversionPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConversionPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConversionPanelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ConversionPanel*
 */
type ConversionPanelSliceVariation = ConversionPanelSliceDefault;

/**
 * ConversionPanel Shared Slice
 *
 * - **API ID**: `conversion_panel`
 * - **Description**: ConversionPanel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConversionPanelSlice = prismic.SharedSlice<
  "conversion_panel",
  ConversionPanelSliceVariation
>;

/**
 * Item in *HeroDemo → Default → Primary → Carousal*
 */
export interface HeroDemoSliceDefaultPrimaryCarousalItem {
  /**
   * Images field in *HeroDemo → Default → Primary → Carousal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.carousal[].images
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  images: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroDemo → Default → Primary*
 */
export interface HeroDemoSliceDefaultPrimary {
  /**
   * Carousal field in *HeroDemo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.carousal[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousal: prismic.GroupField<
    Simplify<HeroDemoSliceDefaultPrimaryCarousalItem>
  >;

  /**
   * Heading field in *HeroDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_demo.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeroDemo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroDemoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroDemoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroDemo*
 */
type HeroDemoSliceVariation = HeroDemoSliceDefault;

/**
 * HeroDemo Shared Slice
 *
 * - **API ID**: `hero_demo`
 * - **Description**: HeroDemo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroDemoSlice = prismic.SharedSlice<
  "hero_demo",
  HeroDemoSliceVariation
>;

/**
 * Item in *MegaMenu → Default → Primary → Column One*
 */
export interface MegaMenuSliceDefaultPrimaryColumnOneItem {
  /**
   * Heading field in *MegaMenu → Default → Primary → Column One*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.column_one[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MegaMenu → Default → Primary → Column One*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.column_one[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Link field in *MegaMenu → Default → Primary → Column One*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.column_one[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *MegaMenu → Default → Primary → Column Two*
 */
export interface MegaMenuSliceDefaultPrimaryColumnsTwoItem {
  /**
   * Heading field in *MegaMenu → Default → Primary → Column Two*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.columns_two[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Links field in *MegaMenu → Default → Primary → Column Two*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.columns_two[].links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *MegaMenu → Default → Primary → ImageColumn*
 */
export interface MegaMenuSliceDefaultPrimaryImagecolumnItem {
  /**
   * Image field in *MegaMenu → Default → Primary → ImageColumn*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.imagecolumn[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *MegaMenu → Default → Primary → ImageColumn*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.imagecolumn[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MegaMenu → Default → Primary → ImageColumn*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.imagecolumn[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Page Link field in *MegaMenu → Default → Primary → ImageColumn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.imagecolumn[].page_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  page_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *MegaMenu → About UsVariation → Primary → Column One*
 */
export interface MegaMenuSliceAboutUsVariationPrimaryColumnOneItem {
  /**
   * Heading field in *MegaMenu → About UsVariation → Primary → Column One*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.column_one[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Link field in *MegaMenu → About UsVariation → Primary → Column One*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.column_one[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *MegaMenu → About UsVariation → Primary → ImageColumn*
 */
export interface MegaMenuSliceAboutUsVariationPrimaryImagecolumnItem {
  /**
   * Image field in *MegaMenu → About UsVariation → Primary → ImageColumn*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.imagecolumn[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *MegaMenu → About UsVariation → Primary → ImageColumn*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.imagecolumn[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Page Link field in *MegaMenu → About UsVariation → Primary → ImageColumn*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.imagecolumn[].page_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  page_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *MegaMenu → Default → Primary*
 */
export interface MegaMenuSliceDefaultPrimary {
  /**
   * Menu ID field in *MegaMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.menu_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_id: prismic.KeyTextField;

  /**
   * Column One field in *MegaMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.column_one[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  column_one: prismic.GroupField<
    Simplify<MegaMenuSliceDefaultPrimaryColumnOneItem>
  >;

  /**
   * Column Two field in *MegaMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.columns_two[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns_two: prismic.GroupField<
    Simplify<MegaMenuSliceDefaultPrimaryColumnsTwoItem>
  >;

  /**
   * ImageColumn field in *MegaMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.default.primary.imagecolumn[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  imagecolumn: prismic.GroupField<
    Simplify<MegaMenuSliceDefaultPrimaryImagecolumnItem>
  >;
}

/**
 * Default variation for MegaMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MegaMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MegaMenuSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MegaMenu → About UsVariation → Primary*
 */
export interface MegaMenuSliceAboutUsVariationPrimary {
  /**
   * Menu ID field in *MegaMenu → About UsVariation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.menu_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_id: prismic.KeyTextField;

  /**
   * Column One field in *MegaMenu → About UsVariation → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.column_one[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  column_one: prismic.GroupField<
    Simplify<MegaMenuSliceAboutUsVariationPrimaryColumnOneItem>
  >;

  /**
   * ImageColumn field in *MegaMenu → About UsVariation → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.aboutUsVariation.primary.imagecolumn[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  imagecolumn: prismic.GroupField<
    Simplify<MegaMenuSliceAboutUsVariationPrimaryImagecolumnItem>
  >;
}

/**
 * About UsVariation variation for MegaMenu Slice
 *
 * - **API ID**: `aboutUsVariation`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MegaMenuSliceAboutUsVariation = prismic.SharedSliceVariation<
  "aboutUsVariation",
  Simplify<MegaMenuSliceAboutUsVariationPrimary>,
  never
>;

/**
 * Slice variation for *MegaMenu*
 */
type MegaMenuSliceVariation =
  | MegaMenuSliceDefault
  | MegaMenuSliceAboutUsVariation;

/**
 * MegaMenu Shared Slice
 *
 * - **API ID**: `mega_menu`
 * - **Description**: MegaMenu
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MegaMenuSlice = prismic.SharedSlice<
  "mega_menu",
  MegaMenuSliceVariation
>;

/**
 * Primary content in *Section2 → Default → Primary*
 */
export interface Section2SliceDefaultPrimary {
  /**
   * Heading field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Section2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section2*
 */
type Section2SliceVariation = Section2SliceDefault;

/**
 * Section2 Shared Slice
 *
 * - **API ID**: `section2`
 * - **Description**: Section2
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section2Slice = prismic.SharedSlice<
  "section2",
  Section2SliceVariation
>;

/**
 * Item in *Section3 → Default → Primary → Group*
 */
export interface Section3SliceDefaultPrimaryGroupItem {
  /**
   * Heading field in *Section3 → Default → Primary → Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.group[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Section3 → Default → Primary → Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.group[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Section3 → Default → Primary → Group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.group[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Section3 → Default → Primary*
 */
export interface Section3SliceDefaultPrimary {
  /**
   * Main Heading field in *Section3 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * Main Description field in *Section3 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.main_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_description: prismic.RichTextField;

  /**
   * Heading field in *Section3 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Section3 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Main Image field in *Section3 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Group field in *Section3 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.default.primary.group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  group: prismic.GroupField<Simplify<Section3SliceDefaultPrimaryGroupItem>>;
}

/**
 * Default variation for Section3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section3SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section3SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section3*
 */
type Section3SliceVariation = Section3SliceDefault;

/**
 * Section3 Shared Slice
 *
 * - **API ID**: `section3`
 * - **Description**: Section3
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section3Slice = prismic.SharedSlice<
  "section3",
  Section3SliceVariation
>;

/**
 * Item in *Section4 → Default → Primary → Cards*
 */
export interface Section4SliceDefaultPrimaryCardsItem {
  /**
   * Link field in *Section4 → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *Section4 → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category  field in *Section4 → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Title field in *Section4 → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Location field in *Section4 → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[].location
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  location: prismic.RichTextField;

  /**
   * Availability Status field in *Section4 → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[].availability_status
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  availability_status: prismic.KeyTextField;

  /**
   * Tags field in *Section4 → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[].tags
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tags: prismic.KeyTextField;
}

/**
 * Item in *Section4 → Default → Primary → Links and Labels*
 */
export interface Section4SliceDefaultPrimaryLinksAndLabelsItem {
  /**
   * Link field in *Section4 → Default → Primary → Links and Labels*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.links_and_labels[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *Section4 → Default → Primary → Links and Labels*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.links_and_labels[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Section4 → Default → Primary*
 */
export interface Section4SliceDefaultPrimary {
  /**
   * Heading field in *Section4 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Section4 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Cards field in *Section4 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<Section4SliceDefaultPrimaryCardsItem>>;

  /**
   * Links and Labels field in *Section4 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.links_and_labels[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links_and_labels: prismic.GroupField<
    Simplify<Section4SliceDefaultPrimaryLinksAndLabelsItem>
  >;

  /**
   * Link field in *Section4 → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *Section4 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Section4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section4SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section4SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section4*
 */
type Section4SliceVariation = Section4SliceDefault;

/**
 * Section4 Shared Slice
 *
 * - **API ID**: `section4`
 * - **Description**: Section4
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section4Slice = prismic.SharedSlice<
  "section4",
  Section4SliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ConversionbarDocument,
      ConversionbarDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataMainLinksItem,
      FooterDocumentDataSubLinksItem,
      FooterDocumentDataSocialLinksItem,
      FooterDocumentDataTestimonialsItem,
      FooterDocumentDataContactsItem,
      FooterDocumentDataFooterCreditsItem,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataMenuItemsItem,
      NavigationDocumentDataSlicesSlice,
      SandboxDocument,
      SandboxDocumentData,
      SandboxDocumentDataSlicesSlice,
      AllDocumentTypes,
      ConversionPanelSlice,
      ConversionPanelSliceDefaultPrimaryPanelItem,
      ConversionPanelSliceDefaultPrimary,
      ConversionPanelSliceVariation,
      ConversionPanelSliceDefault,
      HeroDemoSlice,
      HeroDemoSliceDefaultPrimaryCarousalItem,
      HeroDemoSliceDefaultPrimary,
      HeroDemoSliceVariation,
      HeroDemoSliceDefault,
      MegaMenuSlice,
      MegaMenuSliceDefaultPrimaryColumnOneItem,
      MegaMenuSliceDefaultPrimaryColumnsTwoItem,
      MegaMenuSliceDefaultPrimaryImagecolumnItem,
      MegaMenuSliceDefaultPrimary,
      MegaMenuSliceAboutUsVariationPrimaryColumnOneItem,
      MegaMenuSliceAboutUsVariationPrimaryImagecolumnItem,
      MegaMenuSliceAboutUsVariationPrimary,
      MegaMenuSliceVariation,
      MegaMenuSliceDefault,
      MegaMenuSliceAboutUsVariation,
      Section2Slice,
      Section2SliceDefaultPrimary,
      Section2SliceVariation,
      Section2SliceDefault,
      Section3Slice,
      Section3SliceDefaultPrimaryGroupItem,
      Section3SliceDefaultPrimary,
      Section3SliceVariation,
      Section3SliceDefault,
      Section4Slice,
      Section4SliceDefaultPrimaryCardsItem,
      Section4SliceDefaultPrimaryLinksAndLabelsItem,
      Section4SliceDefaultPrimary,
      Section4SliceVariation,
      Section4SliceDefault,
    };
  }
}
