// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  conversion_panel: dynamic(() => import("./ConversionPanel")),
  hero_demo: dynamic(() => import("./HeroDemo")),
  mega_menu: dynamic(() => import("./MegaMenu")),
  section2: dynamic(() => import("./Section2")),
  section3: dynamic(() => import("./Section3")),
  section4: dynamic(() => import("./Section4")),
  spaces_grid: dynamic(() => import("./SpacesGrid")),
  style_guide: dynamic(() => import("./StyleGuide")),
  the_table: dynamic(() => import("./TheTable")),
  to_page_but_in_slice: dynamic(() => import("./ToPageButInSlice")),
  we_work_hero: dynamic(() => import("./WeWorkHero")),
};
