// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  conversion_panel: dynamic(() => import("./ConversionPanel")),
  hero_demo: dynamic(() => import("./HeroDemo")),
  mega_menu: dynamic(() => import("./MegaMenu")),
  section2: dynamic(() => import("./Section2")),
  section3: dynamic(() => import("./Section3")),
  section4: dynamic(() => import("./Section4")),
  spaces_grid: dynamic(() => import("./SpacesGrid")),
};
