// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_demo: dynamic(() => import("./HeroDemo")),
  section2: dynamic(() => import("./Section2")),
};
